### Get All Products
GET http://localhost:5000/api/products

### Get Single Product
GET http://localhost:5000/api/products/10

### Create New Product
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "title": "labtop ",
     "description": "description description description description description",
     "price": 299
}


###Update Products
PUT  http://localhost:5000/api/products/1
Content-Type: application/json

{
    "title": "product title updated"
}


###Update Products
DELETE  http://localhost:5000/api/products/1
